/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Simple */

#ifndef _Included_Simple
#define _Included_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Simple
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Simple_print
  (JNIEnv *, jobject);

/*
 * Class:     Simple
 * Method:    print_arg
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Simple_print_1arg
  (JNIEnv *, jobject, jint);

/*
 * Class:     Simple
 * Method:    sum_array
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Simple_sum_1array
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
